buildID: "20250627"
namespace: akash-services

image:
  repository: bitnami/kubectl
  tag: latest
  pullPolicy: IfNotPresent

scriptToRun: "/etc/scripts/ticker.sh"
scriptMountPath: "/etc/scripts"

# Node to pin the pod on (set at install/upgrade time)
birthNode: ""

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ .Values.birthNode }}"
