---
apiVersion: v1
kind: ConfigMap
metadata:
  name: akash-provider-paladin-script
  namespace: {{ .Values.namespace | default "akash-services" | quote }}
  labels:
    app: {{ include "akash-provider-paladin.name" . | quote }}
data:
  clear_stuck_pods.sh: |-
{{ .Files.Get "scripts/clear_stuck_pods.sh" | nindent 4 }}
