apiVersion: v1
kind: Service
metadata:
  name: {{ include "akash-provider-paladin.fullname" . }}
  namespace: {{ .Values.namespace | default "akash-services" }}
  labels:
    app: {{ include "akash-provider-paladin.name" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "akash-provider-paladin.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
