apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "akash-provider-paladin.fullname" . }}-paladin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "akash-provider-paladin.name" . }}
