#v2.11.13
BRANCH="stable"
CURRENT_PALADIN_VERSION="2.11.13"
CONFIG="$HOME/akash-provider-paladin/provider.yaml"
#Minium age set to 90min, incase Provider Pod restarts take 1 or 2 minutes, its only about 2-3% of slow periods that the provider pod will be restarting.
PROVIDER_POD_AGE_SECOND_RESTART_TRIGGER=(90*60)
